	<section id="footer" class="section footer">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 align-center">
                    <ul class="footer-links">
                        <li>運営団体：<a href="/about/">大田区立石川台中学校同窓会</a></li>
                        <li><a href="/about/privacy">プライバシーポリシー</a></li>
                        <li><a href="/about/inquiry">お問い合わせ</a></li>
                        <li><a href="/about/recruit">スタッフ募集</a></li>
                    </ul>
				</div>
			</div>

			<div class="row align-center copyright">
					<div class="col-sm-12"><p>Copyright &copy; 2015 大田区立石川台中学校同窓会</p></div>
			</div>
		</div>

	</section>
