<header>
	<div class="header">
	<section id="header" class="appear">
		<div class="navbar navbar-fixed-top" role="navigation" data-0="line-height:100px; height:100px; background-color:rgba(0,204,0,0.3);" data-300="line-height:60px; height:60px; background-color:rgba(0,204,0,1);">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="fa fa-bars color-white"></span>
					</button>
					<h1><a class="navbar-brand" href="/" data-0="line-height:90px;" data-300="line-height:50px;">大田区立石川台中学校同窓会</a></h1>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav" data-0="margin-top:20px;" data-300="margin-top:5px;">
						<li class="active"><a href="#index">Home</a></li>
						<li><a href="#about-event">イベント概要</a></li>
						<li><a href="#frema">フリマ参加</a></li>
						{*<li><a href="#team">Team</a></li>
						<li><a href="#line-pricing">Pricing</a></li>
						<li><a href="#section-works">Portfolio</a></li>
						<li><a href="#section-contact">Contact</a></li>*}
					</ul>
				</div><!--/.navbar-collapse -->
			</div>


	</section>
	</div>
</header>
