	<!-- spacer section:testimonial -->
		<section id="testimonials-3" class="section inter-section" data-stellar-background-ratio="0.5">
		<div class="container">
			<div class="row">
					<div class="col-lg-12">
							<div class="align-center">
										<div class="testimonial pad-top40 pad-bot40 clearfix">
												<p>田園のみどりを超えて　渡り来る風もさやかに</p>
												<p>花匂う自治の学びや　ああ母校石川台中学</p>
												<p>友愛のほほえみ交わし　若き日の希望に燃えて</p>
												<p>集えるわれら</p>
										</div>

								</div>
							</div>
					</div>

			</div>

		</section>
