<section class="featured">
	<div id="index">
			<!-- Responsive slider - START -->
    	<div class="responsive-slider" data-spy="responsive-slider" data-autoplay="true">
			<div class="slides" data-group="slides">
				<ul>
					<li>
						<div class="slide-body" data-group="slide">
							<img src="/ishichu/img/1st/kousha01.jpg" alt="" class="big-screen">
							<img src="/ishichu/img/1st/s/kousha01.jpg" alt="" class="small-screen">
							<div class="caption header" data-animate="slideAppearUpToDown" data-delay="500" data-length="1200">
								<h2>あの頃、ぼくらは石中生だった。</h2>
								<div class="caption-sub" data-animate="slideAppearDownToUp" data-delay="1700" data-length="1200"><p><span>中学時代のことなんて、忘れていた。</span></p></div>
								<div class="caption-sub" data-animate="slideAppearDownToUp" data-delay="2900" data-length="1200"><p><span>でも、懐かしい。</span></p></div>
								<div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="5200" data-length="1200"><h3>そうだ 石中へ行こう！</h3></div>
							</div>
						</div>
					</li>
					<li>
						<div class="slide-body" data-group="slide">
							<img src="/ishichu/img/1st/kousha02.jpg" alt="" class="big-screen">
							<img src="/ishichu/img/1st/s/kousha02.jpg" alt="" class="small-screen">
							<div class="caption header" data-animate="slideAppearDownToUp" data-delay="500" data-length="1200">
								<h2>あの頃、ぼくらは石中生だった。</h2>
								<div class="caption-sub" data-animate="slideAppearUpToDown" data-delay="1700" data-length="1200"><p><span>バカなこともイッパイやった。 </span></p></div>
								<div class="caption-sub" data-animate="slideAppearUpToDown" data-delay="2900" data-length="1200"><p><span>でも一生懸命だった。 </span></p></div>
								<div class="caption-sub" data-animate="slideAppearRightToLeft" data-delay="5200" data-length="1200"><h3>そうだ 石中へ行こう！</h3></div>
							</div>
						</div>
					</li>
  	    		<li>
              <div class="slide-body" data-group="slide">
								<img src="/ishichu/img/1st/kousha03.jpg" alt="" class="big-screen">
                <img src="/ishichu/img/1st/s/kousha03.jpg" alt="" class="small-screen">
                <div class="caption header" data-animate="slideAppearUpToDown" data-delay="500" data-length="1200">
                  <h2>あの頃、ぼくらは石中生だった。</h2>
                  <div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="1700" data-length="1200"><p>いつも賑やかで楽しかった日々。</p></div>
									<div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="2900" data-length="1200"><p>みんな、どうしているんだろう？</p></div>
				  				<div class="caption-sub" data-animate="slideAppearDownToUp" data-delay="5200" data-length="1200"><h3><span>そうだ 石中へ行こう！</span></h3></div>
								</div>
                </div>
  	    		</li>
						<li>
              <div class="slide-body" data-group="slide">
								<img src="/ishichu/img/1st/kousha04.jpg" alt="" class="big-screen">
                <img src="/ishichu/img/1st/s/kousha04.jpg" alt="" class="small-screen">
                <div class="caption header" data-animate="slideAppearUpToDown" data-delay="500" data-length="1200">
                  <h2>あの頃、ぼくらは石中生だった。</h2>
                  <div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="1700" data-length="1200"><p>卒業するまでずっと言えなかった思い。</p></div>
									<div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="2900" data-length="1200"><p>いまなら、言えるだろうか？</p></div>
				  				<div class="caption-sub" data-animate="slideAppearDownToUp" data-delay="5200" data-length="1200"><h3><span>そうだ 石中へ行こう！</span></h3></div>
								</div>
                </div>
  	    		</li>
						<li>
              <div class="slide-body" data-group="slide">
								<img src="/ishichu/img/1st/kousha05.jpg" alt="" class="big-screen">
                <img src="/ishichu/img/1st/s/kousha05.jpg" alt="" class="small-screen">
                <div class="caption header" data-animate="slideAppearUpToDown" data-delay="500" data-length="1200">
                  <h2>あの頃、ぼくらは石中生だった。</h2>
                  <div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="1700" data-length="1200"><p>懐かしい先生、楽しかった部活。</p></div>
									<div class="caption-sub" data-animate="slideAppearLeftToRight" data-delay="2900" data-length="1200"><p>あれがスタート地点だったのかも。</p></div>
				  				<div class="caption-sub" data-animate="slideAppearDownToUp" data-delay="5200" data-length="1200"><h3><span>そうだ 石中へ行こう！</span></h3></div>
								</div>
                </div>
  	    		</li>

  	    	</ul>
		</div>

        <a class="slider-control left" href="#" data-jump="prev"><i class="fa fa-angle-left fa-2x"></i></a>
        <a class="slider-control right" href="#" data-jump="next"><i class="fa fa-angle-right fa-2x"></i></a>


    	</div>
      <!-- Responsive slider - END -->
	</div>
</section>
