	<!--about-->
	<section id="about-event">
		<div class="container">
			<div class="about">
				<div class="row mar-bot40">
					<div class="col-md-offset-3 col-md-6">
						<div class="title">
							<div class="wow bounceIn">
							<h2 class="section-heading animated" data-animation="bounceInUp">秋の一日を石中で<br>楽しみませんか？</h2>
							</div>
						</div>
					</div>
				</div>
				<div class="row">

					<div class="row-slider">
						<div class="col-lg-6 mar-bot30">
							<div class="responsive-slider" data-spy="responsive-slider" data-autoplay="true">
								<div class="slides" data-group="slides">
									<ul>

										<div class="slide-body" data-group="slide">
											<li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event01.png" width="100%" height="350"/></li>
                      <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event02.png" width="100%" height="350"/></li>
                      <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event03.png" width="100%" height="350"/></li>
                      <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event04.png" width="100%" height="350"/></li>
										</div>
									</ul>
										<a class="slider-control left" href="#" data-jump="prev"><i class="fa fa-angle-left fa-2x"></i></a>
										<a class="slider-control right" href="#" data-jump="next"><i class="fa fa-angle-right fa-2x"></i></a>

								</div>
							</div>
						</div>

						<div class="col-lg-6 ">
							<div class="company mar-left10">
								<h4>2015年11月15日（日） 石中の卒業生が世代を超えて協力し、イベントを行います。</h4>
								<p>いままで表向きの活動がなかった石中の同窓会でしたが、2015年度の同窓会は体制を一新し、地域に根ざした活動を通して、現役生にも卒業生にも地域にも貢献していくことを目指します。</p>
                <p>その第一弾となるイベント「そうだ 石中に行こう！」を2015年11月15日（日）に開催します。おいしいものを食べながら、フリーマーケットやさまざまなイベントを通して、秋の一日を石中で一緒に楽しみ、交流の輪を広げましょう。</p>
							</div>
							<div class="list-style">
								<div class="row">
									<div class="col-lg-12 col-sm-12 col-xs-12">
										<ul>
                      <li>掘り出し物を探せ！ フリーマーケット</li>
                      <li>安全＆お買い得 オーガニック野菜即売会</li>
											<li>プロの料理人も腕を振るう イタリアン＆中華</li>
                      <li>父母会提供 特製オーガニック野菜カレー＆豚汁</li>
											<li>わたあめ、駄菓子、あんパンセット</li>
											<li>子どもも大人もチャレンジ！ ストラックアウト</li>
											<li>折り紙クラフト講習会</li>
											<li>同窓会提供：石中思い出ルーム</li>
										</ul>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>

			</div>

		</div>
	</section>
	<!--/about-->
