	<!--about-->
	<section id="about-event">
		<div class="container">
			<div class="about">
				<div class="row">
					<div class="">
						<div class="title">
							<div class="wow bounceIn">
							<h2 class="section-heading">秋の一日を石中で楽しみませんか？</h2>
							</div>
						</div>
					</div>
				</div>
				<div class="row">

					<div class="row-slider">
						<div class="col-lg-6 mar-bot30">
							<div class="responsive-slider" data-spy="responsive-slider" data-autoplay="true">
								<div class="slides" data-group="slides">
										<div class="slide-body" data-group="slide">
									<ul>
										<li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event01.png" width="100%" height="350"/></li>
					                    <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event02.png" width="100%" height="350"/></li>
					                    <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event03.png" width="100%" height="350"/></li>
					                    <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event04.png" width="100%" height="350"/></li>
					                    <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event05.png" width="100%" height="350"/></li>
					                    <li><img alt="" class="img-responsive" src="/ishichu/img/2nd/event06.png" width="100%" height="350"/></li>
									</ul>
										</div>
										<a class="slider-control left" href="#" data-jump="prev"><i class="fa fa-angle-left fa-2x"></i></a>
										<a class="slider-control right" href="#" data-jump="next"><i class="fa fa-angle-right fa-2x"></i></a>

								</div>
							</div>
							<h3 style="line-height:1.5em; font-weight:bold;color:#006400">フリーマーケット開催。出店者募集！</h3>
							<ul>
							<li><span style="font-weight:bold;">募集店数：</span>約50（先着順で締め切り）</li>
							<li><span style="font-weight:bold;">出店料金：</span>1ブース 500円</li>
							<li>参加希望者はこちら⇒<a href="#frema"><span style="font-weight:bold;text-decoration:underline;">参加要項と出店登録</span></a></li>
							</ul>
						</div>

						<div class="col-lg-6 ">
							<div class="company mar-left10">
								<h3 style="line-height:1.5em; font-weight:bold;">11<span class="gray">月</span>15<span class="gray">日</span>（<span class="red">日</span>）は石中へ行こう</h3>
								<p>　２０１５年６月、石川台中学校同窓会は体制を一新しました。そのご挨拶も兼ねて、イベント「そうだ 石中へ行こう！」を2015年11月15日（日）に開催します。石中卒業生が世代を超えて力を合わせ、地域の皆さんと一緒に作り上げたイベントです。おいしいランチ、フリーマーケットや産直野菜販売など、さまざまなお楽しみを用意しました。きっと愉快な秋の一日になることでしょう。</p>
                <p style="font-weight:bold;padding:15px 0;">　昔の石中生、今の石中生、未来の石中生、お近くの皆さん、お待ちしています！</p>
							</div>
							<div class="list-style">
								<div class="row">
									<div class="col-lg-12 col-sm-12 col-xs-12">
										<ul>
											<li>安全＆お買い得 オーガニック野菜即売会</li>
											<li>プロの料理人も腕を振るう イタリアン＆中華</li>
											<li>父母会提供 特製オーガニック野菜カレー＆豚汁</li>
											<li>わたあめ、駄菓子、菓子パンセット</li>
											<li>子どもも大人もチャレンジ！ ストラックアウト＆スピードガン</li>
											<li>作って遊べる、折り紙クラフト</li>
										</ul>
									</div>
								</div>
								<div class="row">
									<p>より詳しいイベント全体図、ガイドはこちら⇒<a href="/eventGuide/" style="font-weight:bold;text-decoration:underline;">イベントガイド</a></p>
								</div>
								<div class="row">
								<div class="col-lg-12 col-sm-12 col-xs-12 well" style="margin-top:20px;padding:15px;border:solid 2px #ffd700;">
									<h3 class="align-center" style="padding:5px;">「同窓会の部屋」で再会を</h3>
									<p>　石中の古い写真を楽しめる「同窓会の部屋」をお訪ねください。懐かしい仲間たちとの再会や、思いがけない出会いがこの部屋で実現しますように。受付で簡単な来場者名簿を作りますから、何回生の誰が来ているか、わかります。</p>
									<p class="align-right">場所：視聴覚室</p>
								</div>
								</div>
								
							</div>
						</div>

					</div>
				</div>

			</div>

		</div>
	</section>
	<!--/about-->
