		<!-- frema -->
		<section id="frema" class="section pad-bot5 bg-white">
		<div class="container">
				<div class="row">
					<div class="col-md-offset-3 col-md-6">
						<div class="section-header">
							<h2 class="section-heading animated">フリーマーケット参加要項と出店登録</h2>
				            <p class="txt-bold align-left">大田区立石川台中学校内にて実施するフリマの参加要項です。出店申し込みのためには以下の出店規約に同意いただく必要があります。</p>
				            <p class="txt-bold align-left"></p>
						</div>
					</div>
				</div>
        <div class="row">
  			<div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12" >
    			<div class="align-left">
				<div class="align-right" style="width:100%;"><button id="disp-rule">出店規約をすべて表示</button><button id="hide-rule" style="display:none;">出店規約を畳む</button></div>
            <div id="frema-rule-box" style="width:100%; height:150px; overflow: scroll;margin:5px auto; border:solid 1px #222; background-color:#eee;padding:0 20px 10px 20px;">
				<h3 class="align-center">【フリーマーケット出店規約】</h3>
				<p>以下の出店規約を遵守頂けないは、以後出店禁止とさせて頂きますのでご注意とご理解をお願い致します。</p>
				<p>&nbsp;</p>
				<p><span class="rule-no txt-bold">1.</span><span class="rule-sentence txt-bold">出店資格</span></p>
				<p><span class="rule-no">①</span><span class="rule-sentence">満18歳以上であること。18歳未満は、保護者同伴が必要。</span></p>
				<p><span class="rule-no">②</span><span class="rule-sentence">行商、路面販売などのプロでないこと。行商や路面販売のプロであるとスタッフが判断した場合は、本規約に基づき、閉店いただきます。</span></p>
				<p><span class="rule-no">③</span><span class="rule-sentence">受付時及び開催中に、スタッフより身分証明書の提示を求められたときは、速やかに提示できること。</span></p>
				<p>&nbsp;</p>
				<p><span class="rule-no txt-bold">2.</span><span class="rule-sentence txt-bold">販売禁止商品および禁止事項</span></p>
				<p><span class="rule-no">①</span><span class="rule-sentence">偽ブランド商品及びコピー品</span></p>
				<p><span class="rule-no">②</span><span class="rule-sentence">海賊版ソフト、アダルトビデオ、その他風紀を乱すもの</span></p>
				<p><span class="rule-no">③</span><span class="rule-sentence">法律に反するもの（麻薬、盗品、銃）</span></p>
				<p><span class="rule-no">④</span><span class="rule-sentence">モデルガン、エアガン、刃物（模造刀含む）</span></p>
				<p><span class="rule-no">⑤</span><span class="rule-sentence">許可していない方の食品、飲食物調理品、及び、ペットフード</span></p>
				<p><span class="rule-no">⑥</span><span class="rule-sentence">生き物</span></p>
				<p><span class="rule-no">⑦</span><span class="rule-sentence">金券</span></p>
				<p><span class="rule-no">⑧</span><span class="rule-sentence">中古自転車</span></p>
				<p><span class="rule-no">⑨</span><span class="rule-sentence">宝石、美術品、骨董品</span></p>
				<p><span class="rule-no">⑩</span><span class="rule-sentence">免許や許可がないと販売できないもの<br/>(医薬品、タバコ、酒類など。但し免許があっても販売禁止とします)。</span></p>
				<p><span class="rule-no">⑪</span><span class="rule-sentence">商品内容に関わらず、クジなどの方法による販売はできません。テキ屋的販売行為禁止</span></p>
				<p><span class="rule-no">⑫</span><span class="rule-sentence">お客様に触れて行う施術行為、マッサージ全般<br/>(免許や資格がある方であっても禁止します)。</span></p>
				<p></p>
				<p>※上記以外におきましても、当日のスタッフの判断により、商品を閉まって頂く場合がございます。<br/>
				※当会で指定するブランド品は、本物・偽者問わず禁止します。<br/>
				販売禁止指定ブランド ： グッチ、ROLEX、ルイヴィトン、エルメス<br/>
				</p>
				<p>&nbsp;</p>
				<p><span class="rule-no txt-bold">3.</span><span class="rule-sentence txt-bold">注意事項</span></p>
				<p><span class="rule-no">①</span><span class="rule-sentence">開催時間厳守。開催時間終了後はすみやかに片付け、退出をしてください。</span></p>
				<p><span class="rule-no">②</span><span class="rule-sentence">搬入搬出は指定の場所、時間を厳守してください。</span></p>
				<p><span class="rule-no">③</span><span class="rule-sentence">指定した出店場所からのはみだし厳禁！出店ブースの譲渡、又貸しはできません<br/>(ブース名義人が一切の責任を負います)。</span></p>
				<p><span class="rule-no">④</span><span class="rule-sentence">貴重品、販売商品（特に高価なもの）は自己管理してください。<br/>※会場内での盗難、置き引き等多発しているため、各自十分注意してください。</span></p>
				<p><span class="rule-no">⑤</span><span class="rule-sentence">開催中に発生した事故については、当会では一切の責任を負えませんのでご注意ください。(人身事故、物損事故等)</span></p>
				<p><span class="rule-no">⑥</span><span class="rule-sentence">会場内での飲食は構いませんが、飲酒は厳禁です。飲酒者を発見した場合は、即時退場とします。</span></p>
				<p><span class="rule-no">⑦</span><span class="rule-sentence">撤収時の清掃は必ず行ってください。<br/>
				開催中に出たゴミを会場に捨てることは厳禁です。<br/>
				(特に飲食物、ダンボール、売れ残りの商品等)<br/>
				※ POPやテープ等のはがし忘れのないように。クラフトテープの使用は禁止です。</span></p>
				<p><span class="rule-no">⑧</span><span class="rule-sentence">会場の施設を傷つけた場合には、原状回復の為の費用をご負担頂きます。</span></p>
				<p><span class="rule-no">⑨</span><span class="rule-sentence">会場内では火気等使用厳禁。<br/>(石油ストーブ、電気ストーブ、電熱機器等の使用は一切禁止です。尚、模擬店については、許可を得た店舗に関し認めます)。</span></p>

				<p><span class="rule-no">⑩</span><span class="rule-sentence">法律に違反する行為の禁止<br/>(例：外国人登録証を持たない方の出店。など)。</span></p>
				<p><span class="rule-no">⑪</span><span class="rule-sentence">高額商品(3,000円以上)の販売には、購入者から求められた場合、連絡先を教えることを義務づけます。</span></p>
				<p><span class="rule-no">⑫</span><span class="rule-sentence">出店マナーや商品に対してのトラブルなど、苦情があった場合、当日の出店は即時中止いただきます。<br/>(禁止行為、暴言、脅迫、恐喝、威嚇、暴力等)</span></p>
				<p><span class="rule-no">⑬</span><span class="rule-sentence">無許可でのアンケート、ビラ配りは禁止致します。確認次第、本部にて回収します。</span></p>
				<p><span class="rule-no">⑭</span><span class="rule-sentence">当日の転売行為禁止。現場での古物の買い取りはできません。</span></p>
				<p><span class="rule-no">⑮</span><span class="rule-sentence">会場で販売した商品に関して、返品の申し出があった場合は、出店者はこれに応じてください。</span></p>
				<p><span class="rule-no">⑯</span><span class="rule-sentence">暴力団やこれに類する反社会団体所属者、及びこれらと密接な関係を有する方の入場はお断りします。</span></p>
				<p><span class="rule-no">⑰</span><span class="rule-sentence">会場スタッフの指示に従わない参加者及び出店者は、退場いただきます。</span></p>
				<p></p>
				<p class="align-right">発行元「そうだ 石中へ行こう！」実行委員会</p>
			</div>
          </div>
        </div>
        <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12" >
			<h3 class="align-center">【フリーマーケット出店登録の注意】</h3>
    		<div class="align-left">
            <p>〇出店には事前登録が必要となります。</p>
            <p>〇記入漏れのないようお願い申し上げます。</p>
            <p>〇出店料金は、1ブース500円となります。開催当日受付にてお支払ください。</p>
            <p>〇全ての内容をご記入されましたら「送信」ボタンを押してください。</p>
            <p>〇FAX送信の場合は、出力いただき、ご記入の上、下記FAX番号まで送信ください。<br/>Fax:03-3726-7148：石川台中学校 和田副校長</p>
            <p></p>
            <p class="small">〇受付が完了しましたら、ご登録いただきましたメールアドレスまで、事務局よりご返信させていただきます。尚、募集ブース数に達した場合、予告無く受付を締め切らせていただきます。</p>
            <p>〇受付完了No.＝出店ブースNo.となります。</p>
            <p>〇登録完了後のキャンセルはできません。無断キャンセルをされた場合は、次回以降の出店をお断りさせていただきます。</p>
            <p>〇今回お送りいただいた情報は、このイベントのみ使用いたします。</p>
    			</div>
          <iframe src="https://docs.google.com/forms/d/1OgV6yTdFsu2XZP5v_I1X68aHSJFXzI2vlURJ_j5agmk/viewform?embedded=true" width="100%" height="2200" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます...</iframe>
  			</div>
      </div>
		</section>
		<!--/frema-->
